[theme]
base = "light"
primaryColor = "#0060AB"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#1A1C1E"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 20

[browser]
gatherUsageStats = false
